name: CI/CD to EC2 Amazon Linux

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt

    - name: Lint code
      run: flake8 .

    - name: Run tests
      run: pytest

    - name: Deploy to EC2 (Amazon Linux)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Kill existing gunicorn (if running)
          pkill gunicorn || true

          # Clone the repo if not present, else pull latest
          cd ~/python-ci-app || git clone https://github.com/${{ github.repository }} ~/python-ci-app
          cd ~/python-ci-app
          git pull origin main

          # Install dependencies
          pip3 install --user -r requirements.txt

          # Run app with gunicorn in background
          nohup ~/.local/bin/gunicorn -w 2 -b 0.0.0.0:80 app:app &
